---
title: "Differential_Exp_Analysis"
author: "Paige Ryan"
date: "2025-03-18"
output: html_document
---

```{r}
cancer_counts <-read.table(file="oral_carcinoma_counts_2018.txt", sep = "\t", header=T)

head(cancer_counts)
```


```{r}
mapping <-select(org.Hs.eg.db, as.character(cancer_counts$ENSEMBL), keytype = "ENSEMBL", column="ENTREZID")

d <- duplicated(mapping$ENSEMBL)
sum(d)
mapping <- mapping[!d,]

cancer_counts <- merge(cancer_counts, mapping, by = "ENSEMBL")
head(cancer_counts)


missing <- is.na(cancer_counts$ENTREZID)
sum(missing)

cancer_counts <- cancer_counts[!missing,]

o <- order(rowSums(cancer_counts[,c(2:7)]), decreasing=TRUE)
cancer_counts <- cancer_counts[o,]
d2 <- duplicated(cancer_counts$ENTREZID)
sum(d2)

cancer_counts <- cancer_counts[!d2,]

mapping2 <- select(org.Hs.eg.db, as.character(cancer_counts$ENTREZID), keytype = "ENTREZID", column="SYMBOL")

d3 <- duplicated(mapping2$ENTREZID)
sum(d3)

mapping2 <- mapping2[!d3,]

cancer_counts <- merge(cancer_counts, mapping2, by = "ENTREZID")
head(cancer_counts)

```
```{r}
y<-DGEList(counts= cancer_counts[,3:8], genes = cancer_counts[,c(1:2,9)])
#head(y$counts)
#head(y$genes)
head(y$samples)
```


```{r}
rownames(y$counts)<- rownames(y$genes)<- y$genes$ENTREZID

y$genes$ENTREZID<-NULL

#head(y$counts)
head(y$genes)
```
```{r}
y<-calcNormFactors(y)
head(y$samples)
```
```{r}
y$samples$group = c("N","T","N","T","N","T")
head(y$samples)
```
```{r}
plotMDS(y)
```
```{r}
y<-estimateDisp(y)
y$common.dispersion
```
```{r}
plotBCV(y)
```
```{r}
et <- exactTest(y, pair=c("N","T"))

summary(de <- decideTests(et))

```
```{r}
detags <- rownames(y)[as.logical(de)]
plotSmear(et, de.tags=detags)
abline(h=c(-1, 1), col="blue")

```
```{r}
diffExpGenes <- topTags(et, n=1000, p.value = 0.05)

head(diffExpGenes$table)
```
```{r}
write.table(diffExpGenes$table, file="tumor_v_normal_exactTest.txt", sep = "\t", row.names=TRUE, col.names=NA)
```


```{r}
Patient <- factor(c(8,8,33,33,51,51))
Tissue <- factor(c("N","T","N","T","N","T"))
design <- model.matrix(~Patient+Tissue)
rownames(design) <- colnames(y)

design

```
```{r}
y <- estimateDisp(y, design, robust=TRUE)

y$common.dispersion 
```
```{r}
fit <- glmFit(y, design)

lrt <- glmLRT(fit, coef=4)

summary(de2 <- decideTests(lrt))
```
```{r}
diffExpGenes2 <- topTags(lrt, n=1000, p.value = 0.05)

head(diffExpGenes2$table)

```


